[project]
name = "sds-common"
version = "2.0.0"
description = "A Python library for common functionality used to interact with SDS."
requires-python = "==3.13.*"
classifiers = [
    "Typing :: Typed",
]
dependencies = [
    "google-auth>=2.57.0",
    "google-cloud-secret-manager>=2.30.0",
    "google-cloud-pubsub>=2.39.2",
    "google-cloud-storage>=3.13.1",
    "google-cloud-firestore>=2.29.0",
    "requests>=2.32.3",
]

[project.optional-dependencies]
impersonation = [
    "google-cloud-iam>=2.25.0",
]

[dependency-groups]
test = [
    "pytest>=8.3.5",
    "pytest-cov>=6.1.1",
    "pytest-xdist>=3.6.1",
    "pytest-order>=1.5.0",
]

lint = [
    "ruff>=0.11.7",
]

publish = [
    "twine>=6.1.0",
    "keyring>=25.6.0",
    "keyrings-google-artifactregistry-auth>=1.1.2",
]

version-check = [
    "toml>=0.10.2",
    "tomlkit>=0.13.3",
]

[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = "--disable-warnings"

[tool.ruff]
line-length = 121
exclude = [ "lib", "__pycache__", ".venv",]

[tool.ruff.lint]
extend-select = ["W292"]

